/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE COMPASSMOT_STATUS PACKING
package com.mavlink.ardupilotmega;
import com.mavlink.MAVLinkPacket;
import com.mavlink.messages.MAVLinkMessage;
import com.mavlink.messages.MAVLinkPayload;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

        
/**
 * Status of compassmot calibration.
 */
public class msg_compassmot_status extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_COMPASSMOT_STATUS = 177;
    public static final int MAVLINK_MSG_LENGTH = 20;
    private static final long serialVersionUID = MAVLINK_MSG_ID_COMPASSMOT_STATUS;

      
    /**
     * Current.
     */
    public float current;
      
    /**
     * Motor Compensation X.
     */
    public float CompensationX;
      
    /**
     * Motor Compensation Y.
     */
    public float CompensationY;
      
    /**
     * Motor Compensation Z.
     */
    public float CompensationZ;
      
    /**
     * Throttle.
     */
    public int throttle;
      
    /**
     * Interference.
     */
    public int interference;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_COMPASSMOT_STATUS;
        
        packet.payload.putFloat(current);
        packet.payload.putFloat(CompensationX);
        packet.payload.putFloat(CompensationY);
        packet.payload.putFloat(CompensationZ);
        packet.payload.putUnsignedShort(throttle);
        packet.payload.putUnsignedShort(interference);
        
        
        return packet;
    }

    /**
     * Decode a compassmot_status message into this class fields
     *
     * @param payload The message to decode
     */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.current = payload.getFloat();
        this.CompensationX = payload.getFloat();
        this.CompensationY = payload.getFloat();
        this.CompensationZ = payload.getFloat();
        this.throttle = payload.getUnsignedShort();
        this.interference = payload.getUnsignedShort();
        
        
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_compassmot_status() {
        this.msgid = MAVLINK_MSG_ID_COMPASSMOT_STATUS;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_compassmot_status( float current, float CompensationX, float CompensationY, float CompensationZ, int throttle, int interference) {
        this.msgid = MAVLINK_MSG_ID_COMPASSMOT_STATUS;

        this.current = current;
        this.CompensationX = CompensationX;
        this.CompensationY = CompensationY;
        this.CompensationZ = CompensationZ;
        this.throttle = throttle;
        this.interference = interference;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_compassmot_status( float current, float CompensationX, float CompensationY, float CompensationZ, int throttle, int interference, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_COMPASSMOT_STATUS;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.current = current;
        this.CompensationX = CompensationX;
        this.CompensationY = CompensationY;
        this.CompensationZ = CompensationZ;
        this.throttle = throttle;
        this.interference = interference;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_compassmot_status(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_COMPASSMOT_STATUS;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from JSON Object
     */
    public msg_compassmot_status(JSONObject jo) {
        this.msgid = MAVLINK_MSG_ID_COMPASSMOT_STATUS;

        readJSONheader(jo);
        
        this.current = (float)jo.optFloat("current");
        this.CompensationX = (float)jo.optFloat("CompensationX");
        this.CompensationY = (float)jo.optFloat("CompensationY");
        this.CompensationZ = (float)jo.optFloat("CompensationZ");
        this.throttle = (int)jo.optInt("throttle");
        this.interference = (int)jo.optInt("interference");
        
        
    }
    
    /**
     * Convert this class to a JSON Object
     */
    public JSONObject toJSON() throws JSONException {
        final JSONObject jo = getJSONheader();
        
        jo.put("current", current);
        jo.put("CompensationX", CompensationX);
        jo.put("CompensationY", CompensationY);
        jo.put("CompensationZ", CompensationZ);
        jo.put("throttle", throttle);
        jo.put("interference", interference);
        
        
        return jo;
    }

                
    /**
     * Returns a string with the MSG name and data
     */
    public String toString() {
        return "MAVLINK_MSG_ID_COMPASSMOT_STATUS - sysid:"+sysid+" compid:"+compid+" current:"+current+" CompensationX:"+CompensationX+" CompensationY:"+CompensationY+" CompensationZ:"+CompensationZ+" throttle:"+throttle+" interference:"+interference+"";
    }
}
        