/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE RANGEFINDER PACKING
package com.mavlink.ardupilotmega;
import com.mavlink.MAVLinkPacket;
import com.mavlink.messages.MAVLinkMessage;
import com.mavlink.messages.MAVLinkPayload;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

        
/**
 * Rangefinder reporting.
 */
public class msg_rangefinder extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_RANGEFINDER = 173;
    public static final int MAVLINK_MSG_LENGTH = 8;
    private static final long serialVersionUID = MAVLINK_MSG_ID_RANGEFINDER;

      
    /**
     * Distance.
     */
    public float distance;
      
    /**
     * Raw voltage if available, zero otherwise.
     */
    public float voltage;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_RANGEFINDER;
        
        packet.payload.putFloat(distance);
        packet.payload.putFloat(voltage);
        
        
        return packet;
    }

    /**
     * Decode a rangefinder message into this class fields
     *
     * @param payload The message to decode
     */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.distance = payload.getFloat();
        this.voltage = payload.getFloat();
        
        
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_rangefinder() {
        this.msgid = MAVLINK_MSG_ID_RANGEFINDER;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_rangefinder( float distance, float voltage) {
        this.msgid = MAVLINK_MSG_ID_RANGEFINDER;

        this.distance = distance;
        this.voltage = voltage;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_rangefinder( float distance, float voltage, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_RANGEFINDER;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.distance = distance;
        this.voltage = voltage;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_rangefinder(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_RANGEFINDER;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from JSON Object
     */
    public msg_rangefinder(JSONObject jo) {
        this.msgid = MAVLINK_MSG_ID_RANGEFINDER;

        readJSONheader(jo);
        
        this.distance = (float)jo.optFloat("distance");
        this.voltage = (float)jo.optFloat("voltage");
        
        
    }
    
    /**
     * Convert this class to a JSON Object
     */
    public JSONObject toJSON() throws JSONException {
        final JSONObject jo = getJSONheader();
        
        jo.put("distance", distance);
        jo.put("voltage", voltage);
        
        
        return jo;
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    public String toString() {
        return "MAVLINK_MSG_ID_RANGEFINDER - sysid:"+sysid+" compid:"+compid+" distance:"+distance+" voltage:"+voltage+"";
    }
}
        