/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* The state of the vehicle's engine transmission, also known as gear. This is typically used in vehicles with internal combustion engines.
*/
public class MAV_ICE_TRANSMISSION_GEAR_STATE {
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_PARK = 0; /* Park. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_NEUTRAL = 1; /* Neutral. Engine is physically disconnected. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD = 2; /* Forward for single gear systems or Variable Transmissions. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_REVERSE = 3; /* Reverse for single gear systems or Variable Transmissions. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_REVERSE_1 = 4; /* Reverse 1. Implies multiple gears exist. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_REVERSE_2 = 5; /* Reverse 2 for faster reverse speeds. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_REVERSE_3 = 6; /* Reverse 3 for faster reverse speeds. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_1 = 7; /* First gear. Implies multiple gears exist. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_2 = 8; /* Second gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_3 = 9; /* Third gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_4 = 10; /* Fourth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_5 = 11; /* Fifth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_6 = 12; /* Sixth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_7 = 13; /* Seventh gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_8 = 14; /* Eighth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_9 = 15; /* Ninth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_ENUM_END = 16; /*  | */
}
            