/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
 * Internal Combusion Engine (ICE) fuel type.
 */
public class MAV_ICE_FUEL_TYPE {
   public static final int MAV_ICE_FUEL_TYPE_GASOLINE = 0; /* Gasoline or Petrol. | */
   public static final int MAV_ICE_FUEL_TYPE_DIESEL = 1; /* Diesel. | */
   public static final int MAV_ICE_FUEL_TYPE_2_STROKE_MIX = 2; /* 2 Stroke Mix. | */
   public static final int MAV_ICE_FUEL_TYPE_KEROSENE = 3; /* Kerosene. | */
   public static final int MAV_ICE_FUEL_TYPE_JET_A_1 = 4; /* Jet A-1. | */
   public static final int MAV_ICE_FUEL_TYPE_JET_B = 5; /* Jet B. | */
   public static final int MAV_ICE_FUEL_TYPE_JET_TS_1 = 6; /* Jet TS-1. | */
   public static final int MAV_ICE_FUEL_TYPE_AVGAS_80 = 7; /* AVGAS 80. | */
   public static final int MAV_ICE_FUEL_TYPE_AVGAS_100 = 8; /* AVGAS 100. | */
   public static final int MAV_ICE_FUEL_TYPE_AVGAS_100LL = 9; /* AVGAS 100LL. | */
   public static final int MAV_ICE_FUEL_TYPE_ENUM_END = 10; /*  | */
}
            