/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* The state of the vehicle's engine transmission, also known as gear. This is typically used in vehicles with internal combustion engines.
*/
public class MAV_ICE_TRANSMISSION_GEAR_STATE {
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_UNKNOWN = 0; /* Unknown. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_PARK = 1; /* Park. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_NEUTRAL = 2; /* Neutral. Engine is physically disconnected. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD = 3; /* Forward for single gear systems or Variable Transmissions. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_REVERSE = 4; /* Reverse for single gear systems or Variable Transmissions. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_REVERSE_1 = 5; /* Reverse 1. Implies multiple gears exist. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_REVERSE_2 = 6; /* Reverse 2 for faster reverse speeds. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_REVERSE_3 = 7; /* Reverse 3 for faster reverse speeds. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_1 = 8; /* First gear. Implies multiple gears exist. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_2 = 9; /* Second gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_3 = 10; /* Third gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_4 = 11; /* Fourth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_5 = 12; /* Fifth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_6 = 13; /* Sixth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_7 = 14; /* Seventh gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_8 = 15; /* Eighth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_FORWARD_9 = 16; /* Ninth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_PWM_VALUE = 17; /* Ninth gear. | */
   public static final int MAV_ICE_TRANSMISSION_GEAR_STATE_ENUM_END = 18; /*  | */
}
            