/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
 * Internal Combusion Engine (ICE) fuel level units.
 */
public class MAV_ICE_FUEL_LEVEL_UNITS {
   public static final int MAV_ICE_FUEL_LEVEL_UNITS_PERCENT = 0; /* Percent. | */
   public static final int MAV_ICE_FUEL_LEVEL_UNITS_POUNDS = 1; /* Pounds. | */
   public static final int MAV_ICE_FUEL_LEVEL_UNITS_KILOGRAMS = 2; /* Kilograms. | */
   public static final int MAV_ICE_FUEL_LEVEL_UNITS_GALLON = 3; /* Gallon. | */
   public static final int MAV_ICE_FUEL_LEVEL_UNITS_LITER = 4; /* Liter. | */
   public static final int MAV_ICE_FUEL_LEVEL_UNITS_ENUM_END = 5; /*  | */
}
            