/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE ICE_FUEL_LEVEL PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Fuel tank/cell level.
*/
public class msg_ice_fuel_level extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_ICE_FUEL_LEVEL = 372;
    public static final int MAVLINK_MSG_LENGTH = 11;
    private static final long serialVersionUID = MAVLINK_MSG_ID_ICE_FUEL_LEVEL;


      
    /**
    * Fuel level - Max. Useful to calculate a percent.
    */
    public float level_max;
      
    /**
    * Fuel level - Current.
    */
    public float level;
      
    /**
    * Index of gearbox transmission to set.
    */
    public short index;
      
    /**
    * Fuel type.
    */
    public short type;
      
    /**
    * Fuel level measurement units.
    */
    public short units;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_ICE_FUEL_LEVEL;
              
        packet.payload.putFloat(level_max);
              
        packet.payload.putFloat(level);
              
        packet.payload.putUnsignedByte(index);
              
        packet.payload.putUnsignedByte(type);
              
        packet.payload.putUnsignedByte(units);
        
        return packet;
    }

    /**
    * Decode a ice_fuel_level message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.level_max = payload.getFloat();
              
        this.level = payload.getFloat();
              
        this.index = payload.getUnsignedByte();
              
        this.type = payload.getUnsignedByte();
              
        this.units = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_ice_fuel_level(){
        msgid = MAVLINK_MSG_ID_ICE_FUEL_LEVEL;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_ice_fuel_level(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_ICE_FUEL_LEVEL;
        unpack(mavLinkPacket.payload);        
    }

              
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_ICE_FUEL_LEVEL - sysid:"+sysid+" compid:"+compid+" level_max:"+level_max+" level:"+level+" index:"+index+" type:"+type+" units:"+units+"";
    }
}
        