/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SET_ICE_TRANSMISSION_STATE PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Select which gear the vehicle engine transmission shall be in. This is usually for vehicles with internal combustion engines.
*/
public class msg_set_ice_transmission_state extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_SET_ICE_TRANSMISSION_STATE = 370;
    public static final int MAVLINK_MSG_LENGTH = 2;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SET_ICE_TRANSMISSION_STATE;


      
    /**
    * Index of gearbox transmission to set.
    */
    public short index;
      
    /**
    * Gear position state.
    */
    public short state;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_SET_ICE_TRANSMISSION_STATE;
              
        packet.payload.putUnsignedByte(index);
              
        packet.payload.putUnsignedByte(state);
        
        return packet;
    }

    /**
    * Decode a set_ice_transmission_state message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.index = payload.getUnsignedByte();
              
        this.state = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_set_ice_transmission_state(){
        msgid = MAVLINK_MSG_ID_SET_ICE_TRANSMISSION_STATE;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_set_ice_transmission_state(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_SET_ICE_TRANSMISSION_STATE;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_SET_ICE_TRANSMISSION_STATE - sysid:"+sysid+" compid:"+compid+" index:"+index+" state:"+state+"";
    }
}
        